import { createClient } from '@supabase/supabase-js';

// Types will be generated by: supabase gen types typescript --linked > packages/til-types/src/database.ts
// For now use a basic client

const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
